# Uncomment the next line to define a global platform for your project
# platform :iOS, '9.0'

target 'Shanli' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shanli
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'FirebaseDatabase'
    pod 'GoogleSignIn'

  target 'ShanliTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShanliUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
